// Preset library — one-click styles that set multiple params at once.
// Each preset specifies a partial snapshot; the store merges it in.

import type { ShapeKind } from "./shapes";
import type { ColorAdjust } from "./color";
import type { FocalConfig } from "./pixelate";
import type { ParamSnapshot, ShapeMixMode, BgMode, LockedPalette } from "./mosaic-store";

export interface Preset {
  id: string;
  name: string;
  jp: string;
  desc: string;
  patch: Partial<ParamSnapshot>;
}

const adj = (a: Partial<ColorAdjust>): ColorAdjust => ({
  brightness: 0,
  contrast: 0,
  saturation: 0,
  hue: 0,
  invert: false,
  ...a,
});

const focal = (f: Partial<FocalConfig>): FocalConfig => ({
  enabled: false,
  x: 0.5,
  y: 0.5,
  falloff: 1.5,
  mode: "center",
  ...f,
});

export const PRESETS: Preset[] = [
  {
    id: "retro-8bit",
    name: "Retro 8-bit",
    jp: "レトロ",
    desc: "Chunky square pixels, 16 colors, slight contrast boost.",
    patch: {
      cellSize: 16,
      shapeSize: 1,
      shape: "square",
      rotation: 0,
      jitter: 0,
      adjust: adj({ contrast: 18, saturation: 12 }),
      quantizeLevels: 16,
      shapeMix: "single",
      shapeMixShapes: ["square"],
      palette: null,
      dither: true,
      bgMode: "paper",
    },
  },
  {
    id: "pointillism",
    name: "Pointillism",
    jp: "点描",
    desc: "Soft circles, sparse fill, paper showing through. Seurat vibes.",
    patch: {
      cellSize: 8,
      shapeSize: 0.6,
      shape: "circle",
      rotation: 0,
      jitter: 0.7,
      adjust: adj({ saturation: 25, brightness: 4 }),
      quantizeLevels: 256,
      shapeMix: "single",
      shapeMixShapes: ["circle"],
      palette: null,
      dither: false,
      bgMode: "paper",
    },
  },
  {
    id: "ukiyo-e",
    name: "Ukiyo-e",
    jp: "浮世絵",
    desc: "Woodblock feel — 8-color palette, triangles, warm tone.",
    patch: {
      cellSize: 12,
      shapeSize: 0.9,
      shape: "triangle",
      rotation: 0,
      jitter: 0.15,
      adjust: adj({ saturation: -10, contrast: 10, hue: -4 }),
      quantizeLevels: 8,
      shapeMix: "single",
      shapeMixShapes: ["triangle"],
      palette: null,
      dither: false,
      bgMode: "paper",
    },
  },
  {
    id: "halftone",
    name: "Halftone",
    jp: "網点",
    desc: "Newspaper dots — small circles, variable density at center.",
    patch: {
      cellSize: 7,
      shapeSize: 0.85,
      shape: "circle",
      rotation: 0,
      jitter: 0,
      adjust: adj({ contrast: 25 }),
      quantizeLevels: 256,
      focal: focal({ enabled: true, mode: "center", falloff: 2.2, x: 0.5, y: 0.5 }),
      shapeMix: "single",
      shapeMixShapes: ["circle"],
      palette: null,
      dither: false,
      bgMode: "paper",
    },
  },
  {
    id: "sumi-e",
    name: "Sumi-e Ink",
    jp: "墨絵",
    desc: "Ink wash — diamonds, desaturated, on cream paper.",
    patch: {
      cellSize: 14,
      shapeSize: 0.9,
      shape: "diamond",
      rotation: 0,
      jitter: 0.3,
      adjust: adj({ saturation: -85, contrast: 22, brightness: 6 }),
      quantizeLevels: 12,
      shapeMix: "single",
      shapeMixShapes: ["diamond"],
      palette: null,
      dither: false,
      bgMode: "paper",
    },
  },
  {
    id: "cross-stitch",
    name: "Cross-stitch",
    jp: "刺繍",
    desc: "Embroidery grid — cross shapes, tight spacing, 14 colors.",
    patch: {
      cellSize: 9,
      shapeSize: 1,
      shape: "cross",
      rotation: 0,
      jitter: 0,
      adjust: adj({ saturation: 10, contrast: 8 }),
      quantizeLevels: 14,
      shapeMix: "single",
      shapeMixShapes: ["cross"],
      palette: null,
      dither: false,
      bgMode: "paper",
    },
  },
  {
    id: "heart-burst",
    name: "Heart-burst",
    jp: "心burst",
    desc: "Hearts of varying size around a focal — fun & playful.",
    patch: {
      cellSize: 14,
      shapeSize: 0.95,
      shape: "heart",
      rotation: 0,
      jitter: 0.2,
      adjust: adj({ saturation: 30, contrast: 10 }),
      quantizeLevels: 32,
      focal: focal({ enabled: true, mode: "center", falloff: 1.8, x: 0.5, y: 0.55 }),
      shapeMix: "single",
      shapeMixShapes: ["heart"],
      palette: null,
      dither: false,
      bgMode: "paper",
    },
  },
  {
    id: "starfield",
    name: "Starfield",
    jp: "星空",
    desc: "Five-point stars, sparse, on ink-black paper. Night sky feel.",
    patch: {
      cellSize: 10,
      shapeSize: 0.7,
      shape: "star",
      rotation: 0,
      jitter: 0.5,
      adjust: adj({ brightness: -10, contrast: 30, saturation: -20 }),
      quantizeLevels: 24,
      shapeMix: "single",
      shapeMixShapes: ["star"],
      palette: null,
      dither: false,
      bgMode: "ink",
    },
  },
  {
    id: "hex-mosaic",
    name: "Hex Mosaic",
    jp: "六角",
    desc: "Honeycomb of hexagons, full color, slight jitter.",
    patch: {
      cellSize: 13,
      shapeSize: 0.92,
      shape: "hexagon",
      rotation: 0,
      jitter: 0.1,
      adjust: adj({ saturation: 8 }),
      quantizeLevels: 256,
      shapeMix: "single",
      shapeMixShapes: ["hexagon"],
      palette: null,
      dither: false,
      bgMode: "paper",
    },
  },
  {
    id: "lum-mix",
    name: "Luminance Mix",
    jp: "光度mix",
    desc: "Three shapes banded by luminance: stars → circles → squares.",
    patch: {
      cellSize: 12,
      shapeSize: 0.9,
      shape: "circle",
      rotation: 0,
      jitter: 0.15,
      adjust: adj({ contrast: 12 }),
      quantizeLevels: 48,
      shapeMix: "luminance",
      shapeMixShapes: ["star", "circle", "square"],
      palette: null,
      dither: false,
      bgMode: "paper",
    },
  },
  {
    id: "paper-cut",
    name: "Paper Cut",
    jp: "切り絵",
    desc: "Bold 4-color palette, big squares — kirie paper-cut look.",
    patch: {
      cellSize: 20,
      shapeSize: 1,
      shape: "square",
      rotation: 0,
      jitter: 0,
      adjust: adj({ contrast: 30, saturation: 15 }),
      quantizeLevels: 4,
      shapeMix: "single",
      shapeMixShapes: ["square"],
      palette: null,
      dither: false,
      bgMode: "paper",
    },
  },
  {
    id: "kaleido",
    name: "Kaleido",
    jp: "万華鏡",
    desc: "Rotated diamonds + heavy jitter + saturated palette.",
    patch: {
      cellSize: 11,
      shapeSize: 0.85,
      shape: "diamond",
      rotation: 45,
      jitter: 0.6,
      adjust: adj({ saturation: 45, contrast: 15, hue: 8 }),
      quantizeLevels: 32,
      shapeMix: "single",
      shapeMixShapes: ["diamond"],
      palette: null,
      dither: false,
      bgMode: "paper",
    },
  },
];
